import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/sections/Navbar";
import SmoothScrolling from "@/components/SmoothScrolling";
import Footer from "@/components/sections/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased max-w-screen box-border">
        {/* <SmoothScrolling> */}
          <Navbar />
          {children}
          <Footer />
        {/* </SmoothScrolling> */}
      </body>
    </html>
  );
}
